/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "us-east-2:bc527562-336b-4523-8690-187b95bd2488",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_QmeqsTRVz",
  "aws_user_pools_web_client_id": "5urbese28dvoik9elait9ss2iq",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_appsync_graphqlEndpoint": "https://ptcwmpnzdrbfznyrx5in3srkky.appsync-api.us-east-2.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-2",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_user_files_s3_bucket": "polly35612-dev",
  "aws_user_files_s3_bucket_region": "us-east-2",
  "aws_content_delivery_bucket": "pollywebapp-20220425071336-hostingbucket-dev",
  "aws_content_delivery_bucket_region": "us-east-2",
  "aws_content_delivery_url": "https://dyyiq8lf168bs.cloudfront.net"
};


export default awsmobile;